name: Release
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: chmod u+x .github/workflows/generic-build.sh .github/workflows/ci-run-tests.sh

      - name: Build for matrix.arch == amd64
        run: |
          sudo .github/workflows/generic-build.sh ${{ matrix.arch }}
          sudo .github/workflows/ci-run-tests.sh ${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: kcov-${{ matrix.arch }}.tar.gz
          path: kcov-${{ matrix.arch }}.tar.gz

  create_release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: kcov-*/kcov-*.tar.gz
          artifactContentType: application/gzip
          token: ${{ secrets.GITHUB_TOKEN }}
